version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - /var/lib/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: BlogApp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
    - 5432:5432
